# Generated by Django 3.2.7 on 2021-10-15 09:19

import django.core.validators
import django_inet.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_peerctl", "0002_auto_20211015_0856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internetexchange",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="network",
            name="asn",
            field=django_inet.models.ASNField(
                db_index=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
