# Generated by Django 3.2.7 on 2021-10-19 11:33

import django.core.validators
import django.db.models.manager
import django_inet.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0017_alter_organizationuser_options"),
        ("django_peerctl", "0008_rename_as_set"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncMacAddress",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="network",
            name="asn",
            field=django_inet.models.ASNField(
                db_index=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
