# Generated by Django 3.2.15 on 2022-09-16 11:23

from django.db import migrations


def delete_all_portinfos(apps, schema_editor):
    PortInfo = apps.get_model("django_peerctl", "PortInfo")
    PortInfo.handleref.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('django_peerctl', '0010_reftag'),
    ]

    operations = [
        migrations.RunPython(delete_all_portinfos, migrations.RunPython.noop),
    ]
