# Generated by Django 3.2.15 on 2022-09-17 10:19

import django.core.validators
import django_inet.models
import fullctl.django.fields.service_bridge
import fullctl.service_bridge.devicectl
from django.db import migrations


def delete_networks(apps, schema_editor):

    Network = apps.get_model("django_peerctl", "Network")
    Network.handleref.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("django_peerctl", "0011_auto_20220916_1123"),
    ]

    operations = [
        migrations.RunPython(delete_networks, migrations.RunPython.noop),
    ]
