# Generated by Django 3.2.15 on 2022-09-17 10:29

import django.core.validators
import django_inet.models
import fullctl.django.fields.service_bridge
import fullctl.service_bridge.devicectl
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_peerctl", "0012_devicectl_reset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="physicalport",
            name="device",
        ),
        migrations.RemoveField(
            model_name="physicalport",
            name="logical_port",
        ),
        migrations.RemoveField(
            model_name="port",
            name="policy4",
        ),
        migrations.RemoveField(
            model_name="port",
            name="policy6",
        ),
        migrations.RemoveField(
            model_name="port",
            name="port_info",
        ),
        migrations.RemoveField(
            model_name="port",
            name="virtual_port",
        ),
        migrations.RemoveField(
            model_name="virtualport",
            name="logical_port",
        ),
        migrations.AlterField(
            model_name="network",
            name="asn",
            field=django_inet.models.ASNField(
                db_index=True,
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="peersession",
            name="port",
            field=fullctl.django.fields.service_bridge.ReferencedObjectField(
                bridge=fullctl.service_bridge.devicectl.Port
            ),
        ),
        migrations.DeleteModel(
            name="Device",
        ),
        migrations.DeleteModel(
            name="LogicalPort",
        ),
        migrations.DeleteModel(
            name="PhysicalPort",
        ),
        migrations.DeleteModel(
            name="Port",
        ),
        migrations.DeleteModel(
            name="VirtualPort",
        ),
    ]
