# Generated by Django 3.2.15 on 2022-09-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_peerctl', '0013_devicectl_reset_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='net_set', to='django_fullctl.organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
