# Generated by Django 3.2.15 on 2022-09-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_peerctl", "0017_portpolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="peerport",
            name="interface_name",
            field=models.CharField(
                blank=True, help_text="Peer interface name", max_length=255, null=True
            ),
        ),
    ]
