# Generated by Django 3.2.16 on 2022-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_peerctl', '0018_peerport_interface_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='email_override',
            field=models.EmailField(blank=True, help_text='Will override the From: address for email communications from this network', max_length=254, null=True),
        ),
    ]
