# Generated by Django 3.2.16 on 2023-01-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_peerctl", "0020_peer_session_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="peersession",
            name="meta4",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="peersession",
            name="meta6",
            field=models.JSONField(null=True),
        ),
    ]
