# Generated by Django 3.2.17 on 2023-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_peerctl', '0023_auto_20230208_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_type_override',
            field=models.CharField(blank=True, choices=[('NSP', 'NSP'), ('Content', 'Content'), ('Cable/DSL/ISP', 'Cable/DSL/ISP'), ('Enterprise', 'Enterprise'), ('Educational/Research', 'Educational/Research'), ('Non-Profit', 'Non-Profit'), ('Route Server', 'Route Server'), ('Network Services', 'Network Services'), ('Route Collector', 'Route Collector'), ('Government', 'Government')], help_text='Network type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='route_server_md5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
