# Generated by Django 3.2.17 on 2023-02-10 11:05

import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_peerctl", "0026_portinfo_is_route_server_peer"),
    ]

    operations = [
        migrations.AddField(
            model_name="portinfo",
            name="mac_address",
            field=netfields.fields.MACAddressField(blank=True, null=True),
        ),
    ]
