# Generated by Django 3.2.17 on 2023-02-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_peerctl', '0029_auto_20230210_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='never_via_route_servers_override',
            field=models.BooleanField(null=True),
        ),
    ]
