# Generated by Django 3.2.17 on 2023-05-15 11:27

import django.db.models.deletion
import django.db.models.manager
import fullctl.django.fields.service_bridge
import fullctl.service_bridge.devicectl
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_fullctl", "0031_auto_20230310_2152"),
        ("django_peerctl", "0031_auto_20230215_1401"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncDevicePorts",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SyncIsRsPeer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="peersession",
            name="device",
            field=fullctl.django.fields.service_bridge.ReferencedObjectField(
                bridge=fullctl.service_bridge.devicectl.Device,
                help_text="Session is running on this device",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="peersession",
            name="peer_port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peer_sessions",
                to="django_peerctl.peerport",
            ),
        ),
    ]
