# Generated by Django 3.2.17 on 2023-05-16 12:12

from django.db import migrations
import django_peerctl.models.peerctl
import fullctl.django.fields.service_bridge
import fullctl.service_bridge.devicectl


class Migration(migrations.Migration):

    dependencies = [
        ('django_peerctl', '0032_auto_20230515_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peersession',
            name='device',
            field=fullctl.django.fields.service_bridge.ReferencedObjectField(blank=True, bridge=fullctl.service_bridge.devicectl.Device, help_text='Session is running on this device', null=True),
        ),
        migrations.AlterField(
            model_name='peersession',
            name='port',
            field=fullctl.django.fields.service_bridge.ReferencedObjectField(blank=True, bridge=django_peerctl.models.peerctl.Port, null=True),
        ),
    ]
