# Generated by Django 3.2.17 on 2023-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_peerctl", "0033_auto_20230516_1212"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="portinfo",
            managers=[],
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="devicetemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="internetexchange",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="peernetwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="peerport",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="peersession",
            name="meta4",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="peersession",
            name="meta6",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="peersession",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="portinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="portpolicy",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Ok"),
                    ("pending", "Pending"),
                    ("deactivated", "Deactivated"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="ok",
                max_length=12,
            ),
        ),
    ]
