# Generated by Django 3.2.14 on 2023-06-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_peerctl", "0036_emailtemplate_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetemplate",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
