# Generated by Django 3.2.23 on 2023-11-18 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_peerctl", "0042_auto_20231118_0857"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="organizationdefaultnetwork",
            table="peerctl_default_network",
        ),
    ]
