# Generated by Django 3.2.20 on 2023-12-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_peerctl", "0044_peer_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policypeergroup",
            name="afi",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="policypeergroup",
            name="allow_asn_in",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="policypeergroup",
            name="enforce_first_asn",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="policypeergroup",
            name="export_policy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="policypeergroup",
            name="import_policy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="policypeergroup",
            name="max_prefixes",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="policypeergroup",
            name="multipath",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="policypeergroup",
            name="soft_reconfig",
            field=models.BooleanField(null=True),
        ),
    ]
